# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: mergebase-task@1
  inputs:
    ScanName: 'MergeBase-From-Azure-Devops-Windows2019'
    CustomerServer: 'demo.mergebase.com'
    CustomerToken: '1K76H7yfB0QWhtDm6s1kLoOeAvS_dYVQY'
    KillBuild: true
    SeverityThreshold: '0.0'
    DebugMode: true

